export const getVisQueryBody = (params) => ({
  ...params,
  pivots: [],
  fill_fields: [],
  filter_expression: '',
  dashboard_elements: '',
  limit: '500',
  column_limit: '',
  total: true,
  row_total: '',
  vis_config: {
    show_view_names: false,
    show_row_numbers: false,
    transpose: false,
    truncate_text: true,
    hide_totals: false,
    hide_row_totals: false,
    size_to_fit: true,
    table_theme: 'white',
    limit_displayed_rows: false,
    enable_conditional_formatting: false,
    header_text_alignment: 'left',
    header_font_size: '12',
    rows_font_size: '12',
    conditional_formatting_include_totals: false,
    conditional_formatting_include_nulls: false,
    show_sql_query_menu_options: false,
    show_totals: true,
    show_row_totals: true,
    series_cell_visualizations: {
      'p2p_exec_fin_2_daily_deepdive_final_cust_look.pct_take_rate': {
        is_active: false,
      },
    },

    series_types: {},
    type: 'looker_grid',
    defaults_version: 1,
  },
  dynamic_fields: '',
  has_table_calculations: false,
})
